version: '3.7'
services:
  deep-learning-app:
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: 2g
    ports:
    - "80:8501"
    networks:
      - app-network
  
  logstash:
    image: logstash:7.17.21
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:7.17.21
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app-network

  kibana:
    image: kibana:7.17.21
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch 
    networks:
      - app-network

volumes:
  elasticsearch-data:

networks:
  app-network: