version: '3.7'
services:
  deep-learning-app:
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-files: "10"

  logstash:
    image: logstash:7.16
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.16
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.16
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch 

volumes:
  elasticsearch-data: